blueprint:
  name: Retry Switch/Light with Entity State Validation
  description: Control an entity and verify success using another entity's state
  domain: automation
  input:
    target_entity:
      name: Device to Control
      description: Entity to turn on/off
      selector:
        entity:
          domain: ["light", "switch"]
    service_to_call:
      name: Service to Execute
      description: Turn on or turn off
      selector:
        select:
          options:
            - turn_on
            - turn_off
    reference_entity:
      name: Validation Entity
      description: Entity to check for success state
      selector:
        entity:
    reference_state:
      name: Expected State
      description: State value that indicates success
      selector:
        text:
    check_period:
      name: Retry Delay
      description: Time between attempts
      selector:
        duration:
    number_retries:
      name: Retry Attempts
      description: Number of retries after initial attempt
      selector:
        number:
          min: 0
          mode: box
    action_on_failure:
      name: Failure Action
      description: Action to execute after all retries fail
      selector:
        action:

variables:
  remaining_retries: !input number_retries

trigger:
  - platform: event
    event_type: retry_entity_validation

action:
  - choose:
      - conditions: "{{ trigger is not defined or trigger.event.data.target_entity != target_entity }}"
        sequence:
          # Initial attempt
          - service: !input service_to_call
            target:
              entity_id: !input target_entity
          - delay: !input check_period
          - condition: template
            value_template: "{{ is_state(input.reference_entity, input.reference_state) }}"
          - if:
              - "{{ not condition }}"
            then:
              - event: retry_entity_validation
                event_data:
                  target_entity: !input target_entity
                  retries: "{{ remaining_retries }}"

    default:
      # Retry sequence
      - variables:
          remaining_retries: "{{ trigger.event.data.retries | int - 1 }}"
      - if:
          - "{{ remaining_retries >= 0 }}"
        then:
          - service: !input service_to_call
            target:
              entity_id: !input target_entity
          - delay: !input check_period
          - condition: template
            value_template: "{{ is_state(input.reference_entity, input.reference_state) }}"
          - if:
              - "{{ not condition }}"
            then:
              - event: retry_entity_validation
                event_data:
                  target_entity: !input target_entity
                  retries: "{{ remaining_retries }}"
        else:
          # Failure action
          - action: !input action_on_failure

mode: restart
